config/routes.rb
Rails.application.routes.draw do

  get 'likes/create'

  get 'profiles/:id' => 'profiles#show', as: :profile

  get 'profiles' => 'profiles#index'


  root 'twits#index'

  resources :twits do
    resources :likes
  end

  resources :relationships
  resources :twits

  get 'twits/index'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :twit
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: "User"
end

app/models/twit.rb
class Twit < ApplicationRecord
  belongs_to :user
  has_many :likes

  validates :message, 
	    presence: true,
	    length: { 
		  maximum: 140,
		  too_long: "Twits can only be 140 characters max" 
		  }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :twits
  has_many :relationships
  has_many :friends, through: :relationships
  has_many :likes

  has_many :inverse_relationships, 
	    class_name: "Relationship", 
	    foreign_key: :friend_id

  has_many :inverse_friends,
	    through: :relationships,
	    source: :user

  validates :username,
	    presence: true,
	    uniqueness: true

  def likes?(twit)
    twit.likes.where(user_id: id).any?
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_perameters, if: :devise_controller?

  protected

  def configure_permitted_perameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit({ roles: [] }, :email, :password, :password_confirmation, :name, :username, :bio, :location)  }

    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit( :email, :password, :password_confirmation, :current_password, :name, :bio, :location, :username)  }

  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_twit

  def create
    @twit.likes.where(user_id: current_user.id).first_or_create
    respond_to do |format|
      format.html { redirect_to request.referrer }
    end
  end

  def destroy
    @twit.likes.where(user_id: current_user.id).destroy_all
    respond_to do |format|
      format.html { redirect_to request.referrer }
    end
  end

  private

  def set_twit
    @twit = Twit.find(params[:twit_id])
  end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_filter :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

  def create
    @relationship = current_user.relationships.build(friend_id: params[:friend_id])

    if @relationship.save
      flash[:notice] = "Followed successfully"
      redirect_to profile_path(current_user.id)
    else
      flash[:notice] = "Unable to follow"
      redirect_to root_path
    end
  end

  def destroy
    @relationship = current_user.relationships.find(params[:id])
    @relationship.destroy
    flash[:notice] = "no longer following"
    redirect_to profile_path(current_user.id)
  end


  private

  def relationship_params
    params.require(:relationship).permit(:friend_id, :user_id)
  end

end

app/controllers/twits_controller.rb
class TwitsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_twit, only: [:show, :edit, :update, :destroy]
  def index
    @twits = Twit.all
  end

  def show
  end

  def edit
  end

  def update
    # before_action @twit = twit.find(params[:id])
    respond_to do |format|
      if @twit.update(twit_params)
	format.html { redirect_to @twit, notice: "Twit updated" }
      else
	format.html { render :edit }
      end
    end
  end

  def new
    @twit = Twit.new
  end

  def create
    @twit = Twit.new(twit_params)
    respond_to do |format|
      if @twit.save 
	format.html { redirect_to @twit, notice: "Twit saved" }
      else
	format.html { render :new }
      end
    end
  end

  def destroy
    @twit.destroy
    respond_to do |format|
      if @twit.destroy
	format.html { redirect_to twits_url, notice: "Twit destroyed" }
      end
    end
  end

  private

  def twit_params
    params.require(:twit).permit(:message, :user_id)
  end

  def set_twit
    @twit = Twit.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/twits_helper.rb
module TwitsHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default nav-out">
  <div class="nav-mid">
    <div class="tab-menu-down">
  <% if user_signed_in? %>
      <%= link_to fa_icon('sign-out 3x'), destroy_user_session_path, method: :delete, class: "pull-right font-awesome-menu", title: 'Sign-out' %>
      <%= link_to fa_icon('users 3x'), profiles_path, class: "pull-right font-awesome-menu", title: 'Users' %>
      <%= link_to fa_icon('user 3x'), profile_path(current_user.id), class: "pull-right font-awesome-menu", title: current_user.username + ' profile' %>
      <%= link_to fa_icon('home 3x'), twits_path, class: "pull-right font-awesome-menu", title: 'Home' %>
  <% else %>
      <%= link_to fa_icon('sign-in 3x'), new_user_session_path, class: "pull-right font-awesome-menu", title: 'Sign-in' %>
      <%= link_to fa_icon('font-awesome 3x'), new_user_registration_path, class: "pull-right font-awesome-menu", title: 'Sign-up' %>
      <%= link_to fa_icon('home 3x'), twits_path, class: "pull-right font-awesome-menu", title: 'Home' %>
  <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tweetter</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%=render '/layouts/navbar' %>


    <div style="padding-top:55px;" class="container-fluid">
    <p id="notice"><%= notice %></p>
      <%= yield %>
    </div>

  </body>
</html>

app/views/likes/create.html.erb
<h1>Likes#create</h1>
<p>Find me in app/views/likes/create.html.erb</p>

app/views/profiles/index.html.erb
<h1>All Users</h1>

<% @users.each do |user| %>
  <%= link_to user.username, profile_path(user) %><br>
<% end %>

app/views/profiles/show.html.erb
<div class="row">
  <div class="col-xs-4">
    <h3><%= @user.name %></h3>
    <h5><%= @user.username %></h5>
    <h5><p><%= @user.bio %></p></h5>
    <h5><%= @user.location %></h5>
    <h5>Joined on <%= @user.created_at.strftime("%B %Y") %></h5>

    <%= @user.relationships.count %> Following
    <br>
    <% @user.relationships.each do |relationship| %>
      <%= link_to relationship.friend.name, profile_path(relationship.friend) %>
    <% end %>
    <br>
    <br>
    <%= pluralize(@user.inverse_relationships.count, "Followers") %>
    <br>
    <% @user.inverse_friends.each do |friend| %>
      <%= link_to friend.name, profile_path(friend) %><br>
    <% end %>
  </div>


  <div class="col-xs-7">
    <div class="panel panel-default">
      <% @user.twits.each do |twit| %>
	<div class="panel-body">
	  <strong>
	    <%= twit.user.username %> 
	  </strong>
	  <small>
	    <%= time_ago_in_words(twit.created_at) %> ago
	  </small>
	  <br>
	  <br>
	  <%= twit.message %>
	</div>
      <% end %>
    </div>
  </div>
</div>
<br>
<br>
<% if current_user.id != @user.id %>
  <% if current_user.friends.include?(@user) %>
    <%= link_to "Unfollow",
	relationship_path(current_user.relationships.find_by_friend_id(@user)),
	method: :delete %>
  <% else %>
    <%= link_to "Follow", 
	relationships_path(friend_id: @user), 
	method: :post %>
  <% end %>
<% end %>

app/views/shared/_likes.html.erb
<% if current_user.likes?(@twit) %>
  <%= link_to "Unlike", twit_like_path(@twit), method: :delete %>
<% else %>
  <%= link_to "Like", twit_likes_path(@twit), method: :post %>
<% end %>
<br>
<%= @twit.likes.count %> Like
<br>
Liked by: 
<% @twit.likes.each do |like| %>
  <br>
  <%= like.user.username %>
  <br>
<% end %>

app/views/twits/_form.html.erb
<%= form_for(@twit) do |f| %>
  <!--*****************-->
  <!-- check for errors -->
  <!--*****************-->
  <% if @twit.errors.any? %>
    <div id="error_explanation">
      <h2>
	<%= pluralize(@twit.errors.count, "error") %> prohibited this tweet from being saved:
      </h2>
      <!-- this loops through the errors -->
      <ul>
	  <% @twit.errors.full_messages.each do |error| %>
	<li>
	  <%= error %>
	</li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <!--*****************-->
  <!--*****************-->
  <!-- the actual form -->
  <!--*****************-->
  <!--*****************-->

  <div class="field form-group">
    <%= f.label :message %>
    <%= f.text_field :message, class: "form-control" %>
  </div>

  <div class="field form-group">
    <%= f.hidden_field :user_id, value: current_user.id %>
  </div>

  <div class="action form-group">
    <%= f.submit class: "btn btn-sm btn-success" %>
  </div>

<% end %>

app/views/twits/edit.html.erb
<h1>Edit Twits</h1>

<%= render 'form' %>

<%= link_to 'Show this twit', @twit, class: "btn btn-sm btn-default" %>

<%= link_to 'Show all twits', twits_path, class: "btn btn-sm btn-default" %>

app/views/twits/index.html.erb
<h1 style="padding-top:1px;">Welcome to Tweeter</h1>

<%= link_to "New Twit", new_twit_path, class: "btn btn-xs btn-success" %>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>
	Message
      </th>
      <th>
	User
      </th>
      <th colspan="3">
      </th>
    </tr>
  </thead>

  <tbody>
    <% @twits.each do |twit| %>
      <tr>
	<td>
	  <%= twit.message %>
	</td>
	<td>
	  <%= twit.user.username %>
	</td>
	<td>
	  <%= link_to "show", twit, class: "btn btn-sm btn-default" %>
	</td>
	<td>
	  <%= link_to "Edit", edit_twit_path(twit), class: "btn btn-sm btn-default" %>
	</td>
	<td>
	  <%= link_to "Destroy", twit, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-sm btn-danger" %>
	</td>
      </tr>
      </tr>
    <% end %> 
  </tbody>

</table>

app/views/twits/new.html.erb
<h1>New Twit</h1>

<%= render 'form' %>

<%= link_to 'See all the twits', twits_path, class: "btn btn-sm btn-default" %>

app/views/twits/show.html.erb
<p>
  <strong>
    Message: 
  </strong>
  <%= @twit.message %>
  <p>
    <strong>
      User: 
    </strong>
    <%= @twit.user.username %>
  </p>
  <br>
  <%= render '/shared/likes' %>
  <br>
</p>

<%= link_to 'Edit this twit', edit_twit_path(@twit), class: "btn btn-sm btn-default" %>
<%= link_to 'Show all twits', twits_path, class: "btn btn-sm btn-default" %>